services:
  pgvector:
    build:
      context: .
      dockerfile: pgvector.Dockerfile
    ports:
      - "127.0.0.1:${EIGEN_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD:-passwd}
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    shm_size: 32g
    cpus: "${EIGEN_CPUS:-16}"
    mem_limit: "${EIGEN_MEMORY:-64g}"
volumes:
  pgvector-data:
